export const items = [
  {
    id: 9,
    name: "Łańcuch",
    level: 1,
    parentItem: "0",
    parentId: null,
    parentClassName: null,
    quantity: 1,
    className: "chain",
    leadTime: 2,
    lotSize: 90,
    inStock: 40,
  },
  {
    id: 1,
    name: "Koło",
    level: 1,
    parentItem: "0",
    parentId: null,
    parentClassName: null,
    quantity: 4,
    className: "wheel",
    leadTime: 2,
    lotSize: 80,
    inStock: 70,
  },
  {
    id: 2,
    name: "Szprycha",
    level: 2,
    parentItem: "Koło",
    parentId: 1,
    parentClassName: "wheel",
    quantity: 1,
    className: "spoke",
    leadTime: 1,
    lotSize: 50,
    inStock: 140,
  },
  {
    id: 3,
    name: "Opona",
    level: 2,
    parentItem: "Koło",
    parentId: 1,
    parentClassName: "wheel",
    quantity: 2,
    className: "tire",
    leadTime: 1,
    lotSize: 120,
    inStock: 230,
  },
  {
    id: 4,
    name: "Rama",
    level: 1,
    parentItem: "0",
    parentId: null,
    quantity: 1,
    className: "frame",
    parentClassName: "frame",
    leadTime: 1,
    lotSize: 70,
    inStock: 40,
  },
  {
    id: 5,
    name: "Kierownica",
    level: 2,
    parentItem: "Rama",
    parentId: 4,
    quantity: 1,
    className: "handlebar",
    parentClassName: "frame",
    leadTime: 1,
    lotSize: 60,
    inStock: 80,
  },
  {
    id: 6,
    name: "Siodło",
    level: 2,
    parentItem: "Rama",
    parentId: 4,
    parentClassName: "frame",
    quantity: 1,
    className: "saddle",
    leadTime: 1,
    lotSize: 90,
    inStock: 60,
  },
  {
    id: 7,
    name: "Hamulec",
    level: 2,
    parentItem: "Rama",
    parentId: 4,
    parentClassName: "frame",
    quantity: 2,
    className: "brake",
    leadTime: 1,
    lotSize: 80,
    inStock: 40,
  },
  {
    id: 8,
    name: "Pedały",
    level: 2,
    parentItem: "Rama",
    parentId: 4,
    parentClassName: "frame",
    quantity: 2,
    className: "pedal",
    leadTime: 1,
    lotSize: 100,
    inStock: 75,
  },
];

export const categoriesData = [
  { name: "Całkowite zapotrzebowanie", className: "grossRequirements" },
  { name: "Planowane przyjęcia", className: "scheduledReceipts" },
  { name: "Przewidywane na stanie", className: "projectedAvailable" },
  { name: "Zapotrzebowanie netto", className: "netRequirements" },
  { name: "Planowane zamówienia", className: "plannedOrderReleases" },
  {
    name: "Planowane przyjęcie zamówień",
    className: "plannedOrderReceipts",
  },
];

export const productionParameters = [
  { name: "Czas realizacji", className: "leadTime" },
  { name: "Wielkość partii", className: "lotSize" },
  { name: "Ilość", className: "quantity" },
  { name: "Na stanie", className: "inStock" },
];
