export const items = [
  {
    name: "Koło",
    level: 1,
    parentItem: "0",
    quantity: 2,
    className: "wheel",
    leadTime: 1,
    lotSize: 1,
    inStock: 1,
  },
  {
    name: "Szprycha",
    level: 2,
    parentItem: "Koło",
    quantity: 64,
    className: "spoke",
    leadTime: 1,
    lotSize: 1,
    inStock: 1,
  },
  {
    name: "Opona",
    level: 2,
    parentItem: "Koło",
    quantity: 2,
    className: "tire",
    leadTime: 1,
    lotSize: 1,
    inStock: 1,
  },
  {
    name: "Rama",
    level: 1,
    parentItem: "0",
    quantity: 1,
    className: "frame",
    leadTime: 1,
    lotSize: 1,
    inStock: 1,
  },
  {
    name: "Kierownica",
    level: 2,
    parentItem: "Rama",
    quantity: 1,
    className: "handlebar",
    leadTime: 1,
    lotSize: 1,
    inStock: 1,
  },
  {
    name: "Siodło",
    level: 2,
    parentItem: "Rama",
    quantity: 1,
    className: "saddle",
    leadTime: 1,
    lotSize: 1,
    inStock: 1,
  },
  {
    name: "Hamulec",
    level: 2,
    parentItem: "Rama",
    quantity: 2,
    className: "brake",
    leadTime: 1,
    lotSize: 1,
    inStock: 1,
  },
  {
    name: "Pedały",
    level: 2,
    parentItem: "Rama",
    quantity: 2,
    className: "pedal",
    leadTime: 1,
    lotSize: 1,
    inStock: 1,
  },
  {
    name: "Łańcuch",
    level: 1,
    parentItem: "0",
    quantity: 1,
    className: "chain",
    leadTime: 1,
    lotSize: 1,
    inStock: 1,
  },
];

export const categoriesData = [
  { name: "Całkowite zapotrzebowanie", className: "gross-requirements" },
  { name: "Planowane przyjęcia", className: "scheduled-receipts" },
  { name: "Przewidywane na stanie", className: "projected-available" },
  { name: "Zapotrzebowanie netto", className: "net-requirements" },
  { name: "Planowane zamówienia", className: "planned-order-releases" },
  {
    name: "Planowane przyjęcie zamówień",
    className: "planned-order-receipts",
  },
];

export const productionParameters = [
  { name: "Czas realizacji", className: "leadTime" },
  { name: "Wielkość partii", className: "lotSize" },
  { name: "Ilość", className: "quantity" },
  { name: "Na stanie", className: "inStock" },
];
